### ISSUE TITLE
GitHubレポジトリへの動線を追加する

### ISSUE THREAD

**Issue by exoego** [shule517/nagoya-benkyokai#29]
名古屋勉強会らむだに何年もお世話になっていますが、オープンソースであることを初めて知りました。

ユーザーが

* 要望を出したり
* できそうなものはプルリクエストをしたり

できるように、らむだから本レポジトリへのリンクを追加するのはどうでしょうか。

**Comment by shule517** [comment]
@exoego issue & PRの対応をして頂いて、ありがとうございました！
せっかくコード公開してるなら、OSSであることを明記して、要望＆PRを受け取れた方がいいですよね。
https://github.com/shule517/nagoya-benkyokai/pull/32 問題ないのでマージします。
