### ISSUE TITLE
主催者と参加者に同じ人が重複表示される

### ISSUE THREAD

**Issue by exoego** [shule517/nagoya-benkyokai#41]
同じアイコンが表示されて不思議に思いました。
主催者はほとんどの場合参加者でもあるはずので、重複を取り除いて主催者だけ表示されれば驚きがないように思います。
![image](https://user-images.githubusercontent.com/127635/61179416-c1babc80-a63c-11e9-8d1e-07413076bd91.png)

**Comment by shule517** [comment]
@exoego 重複はずした方が自然ですね！ 対応ありがとうございます。
